[project]
name = "nader"
version = "0.1.0"
description = "Your project description"
authors = [{ name = "Your Name", email = "your@email.com" }]
dependencies = []

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"